[project]
name = "adk-neo4j"
version = "0.1.0"
description = "ADK Neo4j integration with Jupyter notebooks"
requires-python = ">=3.11"
dependencies = [
    "google-adk==1.5.0",
    "neo4j==5.28.1",
    "litellm==1.73.6",
    "jupyter>=1.0.0",
    "ipykernel>=6.0.0",
    "notebook>=7.0.0",
]
